# coding=utf-8
"""
System Environment Variables
"""
__all__ = (
  "GIT",
  "INTERNET",
  "EMAIL",
  "ORG",
  "TOKEN",
  "HTTPASSWD_BCRYPT_INTERNET",

  "CF_ACCOUNT_ID",
  "CF_API_KEY",
  "CF_API_TOKEN",
  "CF_CA_KEY",
  "CF_EMAIL",
  "CF_ZONE_ID",
  "CF_API_EMAIL",
  "CF_API_DOMAIN",

  "DOCKER_HUB_TOKEN",
  "DOCKER_SYNC_TOKEN",

  "DOPPLER_TOKEN",
  "DOPPLER_ENV",

  "DUCKDNS_TOKEN",

  "FLIT_PASSWORD",
  "FLIT_USERNAME",

  "GH_TOKEN",

  "GITHUB_TOKEN",

  "HOMEBREW_GITHUB_API_TOKEN",

  "ID_RSA",
  "ID_RSA_PUB",

  "JETBRAINS_PERMANET_TOKEN",

  "NPM_EMAIL",
  "NPM_REGISTRY",
  "NPM_SCOPE",
  "NPM_TOKEN",
  "NPM_USER",
  "NPM_PUBLISH",

  "PYPI_API_TOKEN",
  "PYPI_CLEANUP_PASSWORD",

  "SCALEWAY_SECRET_KEY",
  "SCALEWAY_ACCESS_KEY",
  "SCW_TOKEN",
  "SCALEWAY_ORGANIZATION_ID",
  "SCALEWAY_ENDPOINT",

  "TWINE_PASSWORD",
  "TWINE_USER",

  "TWITTER_CONSUMER_API_KEY",
  "TWITTER_CONSUMER_API_SECRET_KEY",
  "TWITTER_ACCESS_TOKEN",
  "TWITTER_ACCESS_TOKEN_SECRET",

  "VERCEL_TOKEN",

  "VULTR_API_KEY",
)

from .noset import NOSET

"""GitHub User"""
GIT: str | NOSET | None = NOSET
"""Internet Password"""
INTERNET: str | NOSET | None = NOSET
"""User Email"""
EMAIL: str | NOSET | None = NOSET
"""GitHub Organization"""
ORG: str | NOSET | None = NOSET
"""GitHub Token"""
TOKEN: str | NOSET | None = NOSET
"""Bcrypt Http User Password"""
HTTPASSWD_BCRYPT_INTERNET: str | NOSET | None = NOSET

CF_ACCOUNT_ID: str | NOSET | None = NOSET
CF_API_KEY: str | NOSET | None = NOSET
CF_API_TOKEN: str | NOSET | None = NOSET
CF_CA_KEY: str | NOSET | None = NOSET
CF_EMAIL: str | NOSET | None = NOSET
CF_ZONE_ID: str | NOSET | None = NOSET
CF_API_EMAIL: str | NOSET | None = NOSET
CF_API_DOMAIN: str | NOSET | None = NOSET

DOCKER_HUB_TOKEN: str | NOSET | None = NOSET
DOCKER_SYNC_TOKEN: str | NOSET | None = NOSET

DOPPLER_TOKEN: str | NOSET | None = NOSET
DOPPLER_ENV: str | NOSET | None = NOSET

DUCKDNS_TOKEN: str | NOSET | None = NOSET

FLIT_PASSWORD: str | NOSET | None = NOSET
FLIT_USERNAME: str | NOSET | None = NOSET

GH_TOKEN: str | NOSET | None = NOSET

GITHUB_TOKEN: str | NOSET | None = NOSET

HOMEBREW_GITHUB_API_TOKEN: str | NOSET | None = NOSET

ID_RSA: str | NOSET | None = NOSET
ID_RSA_PUB: str | NOSET | None = NOSET

JETBRAINS_PERMANET_TOKEN: str | NOSET | None = NOSET

NPM_EMAIL: str | NOSET | None = NOSET
NPM_REGISTRY: str | NOSET | None = NOSET
NPM_SCOPE: str | NOSET | None = NOSET
NPM_TOKEN: str | NOSET | None = NOSET
NPM_USER: str | NOSET | None = NOSET
NPM_PUBLISH: str | NOSET | None = NOSET

PYPI_API_TOKEN: str | NOSET | None = NOSET
PYPI_CLEANUP_PASSWORD: str | NOSET | None = NOSET

SCALEWAY_SECRET_KEY: str | NOSET | None = NOSET
SCALEWAY_ACCESS_KEY: str | NOSET | None = NOSET
SCW_TOKEN: str | NOSET | None = NOSET
SCALEWAY_ORGANIZATION_ID: str | NOSET | None = NOSET
SCALEWAY_ENDPOINT: str | NOSET | None = NOSET

TWINE_PASSWORD: str | NOSET | None = NOSET
TWINE_USER: str | NOSET | None = NOSET

TWITTER_CONSUMER_API_KEY: str | NOSET | None = NOSET
TWITTER_CONSUMER_API_SECRET_KEY: str | NOSET | None = NOSET
TWITTER_ACCESS_TOKEN: str | NOSET | None = NOSET
TWITTER_ACCESS_TOKEN_SECRET: str | NOSET | None = NOSET

VERCEL_TOKEN: str | NOSET | None = NOSET

VULTR_API_KEY: str | NOSET | None = NOSET
