# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem 'activesupport'
# gem 'addressable'
# gem 'bootsnap'
# gem 'bundler'
# gem 'byebug'
# gem 'concurrent-ruby'
# gem 'docile'
# gem 'ecma-re-validator'
# gem 'http-cookie'
# gem 'json_schemer'
# gem 'mechanize'
# gem 'minitest'
# gem 'nokogiri'
# gem 'parallel_tests'
# gem 'parlour'
# gem 'patchelf'
# gem 'plist'
# gem 'ronn'
# gem 'rspec'
# gem 'rspec-github'
# gem 'rspec-its'
# gem 'rspec_junit_formatter'
# gem 'rspec-retry'
# gem 'rspec-sorbet'
# gem 'rspec-wait'
# gem 'rubocop'
# gem 'rubocop-ast'
# gem 'rubocop-performance'
# gem 'rubocop-rails'
# gem 'rubocop-rspec'
# gem 'rubocop-sorbet'
# gem 'ruby-macho'
# gem 'simplecov'
# gem 'simplecov-cobertura'
# gem 'simplecov-html'
# gem 'sorbet-runtime'
# gem 'sorbet-runtime-stub'
# gem 'tapioca'
# gem 'warning'
# gem 'webrobots'
