#!/usr/bin/python3

import sys

IS_IPYTHON = hasattr(__builtins__, '__IPYTHON__')
IS_REPL = hasattr(sys, 'ps1') or IS_IPYTHON or sys.argv[0] == '' or sys.__stdin__.isatty() \
          or 'pythonconsole' in sys.stdout.__class__.__module__
IS_TTY = sys.__stdin__.isatty() or sys.__stdout__.isatty()

try:
    import rich.pretty
    import rich.console
    import rich
    from rich import inspect
    from functools import partial

    ins = partial(rich.inspect, docs=False, methods=True, private=True)
    rinspect = rich.inspect
    console = rich.console.Console(color_system='256')
    cp = console.print
    rich.pretty.install(console=console, expand_all=True)
except ModuleNotFoundError:
    pass

try:
    from ghapi.all import GhApi

    ghapi = GhApi()
except ModuleNotFoundError:
    pass

if IS_IPYTHON:
    '%rehashx'
